name: click_extensions
description: Extensions para formatar dados
version: 1.0.3
repository: https://github.com/ferdead/click-extensions

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  click_functions_helper: ^1.0.1
  intl: ^0.17.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
